### PR TITLE
[DNM] Personal Life tests (and other goodies) [DEPRECATED]

### PR DESCRIPTION
**Pull request by j6k4m8**
@molliem — definitely want your feedback on this, I've made quite a few decisions when implementing that are pending your approval!

This begins to address #9.

---

### Reorganized module
I moved things around slightly to enable modules to import common utilities like `Document`. I arbitrarily named the python module `genderbias` — obviously, that's changeable! 

In particular, I moved tests out of the same file as `Document`, and gave the `Document` class its own file in `document.py`. That way, subodules, such as `genderbias.personal_life`, can reference `Document` if needed. @neiljp, I know you were the latest to touch that code — please feel free to yell at me if I misunderstood or misinterpreted your architecture!

### `Document`s from strings
Now, you can also create a document by passing a string directly; use `Document("my sentence")` or `Document("./my-file.txt")`. 

### Tests directory
I moved all tests to live in the `tests/` top-level directory in pursuit of making it easier to keep track of what tests need to be run for what. I also switched the test-runner to `nose`, which I don't feel strongly enough about to make waves, if anyone else feels strongly that `pytest` is the right way to go.

My favorite thing about `nose` + `unittest` is that it's standard-library, so everyone's guaranteed to have it, and now running `nosetests` in the root directory will automatically hunt down all tests and run them and print a nice report. You can also run `./test.sh` in case we decide to add extra functionality or commandline flags here.

### pipenv
I also added support for [`pipenv`](https://docs.pipenv.org/), which I think will make life a lot easier, especially as we have more people contributing with more dependencies. But this is strictly opt-in, so you can totally ignore. I also added a companion `requirements.txt` so new users can `pip install -r ./requirements.txt` to get all of the packages we use. (It took me a bit to track down dependencies so I thought I'd save others the hassle.)

---

Please let me know if I jumped the gun on any of these things! Not trying to be presumptuous, just trying to maximize helpfulness :)

### CODE REVIEW

**Comment by j6k4m8** [comment]
If you'd like, I can also set us up with CircleCI or another service that will automatically run tests on new pull-requests so that maintainers can see at-a-glance if the new contribution breaks anything.

**Comment by j6k4m8** [comment]
I've made a few more changes to make this more usable from the start. In particular, I reorganized this into a Python module:

```
bin/
    genderbias

genderbias/
    personal_life/
    effort/
```

What this means is that you can now access a particular check using `import genderbias.personal_life`.

I also added a more consistent architecture for checkers so that it'll be more obvious to future developers how to create something that is perfectly harmonious with the rest of the existing library.

A `Detector` class (`genderbias/detector.py`) accepts a document and runs its own flavor of check: So there's a `PersonalLifeDetector`, and I ported @cmd16's work into a `EffortDetector`. (Catherine, please let me know if I did a bad job!)

You can create a `Document` using @neiljp's work, and pass it into the `Detector` like so:

```python
from genderbias import Document, ALL_DETECTORS

letter = """
This lady is good. She's basically the lab mother!

Signed,
Jerk M.D.
"""

doc = Document(letter)

flags = []
for detector in ALL_DETECTORS:
    flags += detector().flag_words(doc)

print("\n".join(str(f) for f in flags))
```

And this will return a list of issues based upon ALL of the issues anyone has ever implemented.

---

This seems like a pretty common use-case, so I converted this into a command-line-executable script, again borrowing syntax from @cmd16.

I ran this on a test file; this is what happens:

```shell
genderbias --file ./example_letters/letterofRecM
[0-0]: This document has a high ratio of words suggesting effort to words suggesting concrete accomplishment.
[674-685]: Effort vs Accomplishment: The word 'willingness' tends to speak about effort more than accomplishment. (Try replacing with phrasing that emphasizes accomplishment.)
```

Woo! It outputs a list of issues, and suggestions!

To get yours to do this too:

- Check out my branch (`git clone https://github.com/j6k4m8/gender-bias/ && cd gender-bias && git checkout personal-life`)
- Install this module; `pip install -e .` from inside the top-level directory. This will install the `genderbias` package so you can access it from Python, and it will also add the `genderbias` tool to your command-line.
- Use the tool! `genderbias --file [your file]`

**Comment by neiljp** [comment]
Hi @j6k4m8, This looks like some *great* changes, but a lot in one pull request, and only in one commit? (except the contributor detail)

I'm aware this is an early/new project, but would it be reasonable for you to split the changes into many much smaller commits that are easier to assess? Even separate PRs. You've also ended up adjusting the code somewhat to do more than just the original issue, which again is great for covering a lot of ground - but can end up with a lot of comments/reviews/changes, based on my previous experience.

**Comment by j6k4m8** [comment]
Agreed — am already working on a split up version!! Small PRs always
better. But my implementation for personal life checks branches from the
module style architecture so I left this here temporarily as a manifest of
all proposed changes. I'll tag you in the more atomic PRs if you'd be
willing to do some code review before merge?

**Comment by neiljp** [comment]
I'm definitely up for some code review to help things along.

Do you have a plan as to how to break it down? Some changes are likely more straightforward than others, but there are a lot of primary design decisions/changes you've made. For that reason there could be a lot of dependencies between PRs/commits - though that's the challenge with doing a lot of development in larger PRs/commits before pushing/reviewing, I suppose ;)

**Comment by j6k4m8** [comment]
Closing this one in favor of #23, #24, and (a final Personal Life implementation, probably #25)

**Pull request closed without merging**
