### PR TITLE
Modify report to accept an optional bias argument when adding flags

### PR DESCRIPTION
**Pull request by neiljp**
Following discussion on slack, this presents a first approach to this issue.

Note:
* String output via `__str__` only selects "negative" flags, and a separate parameterised function would be necessary to change this cleanly, I feel.
* The `to_dict` output is changed to have a bias prefix.
* No code outside `Report` should be impacted at this stage.

This prompted tidying of the existing tests, which makes them also quite a bit cleaner :)

### CODE REVIEW

**Comment by neiljp** [comment]
I have one minor update to this which checks the bounds of the bias are between 0.0-1.0 and raises an exception otherwise, but will hold off for now since I'm aware I already asked for review.

**Comment by neiljp** [comment]
@cmd16 Shall I leave you to adapt effort/accomplishment?

**Comment by neiljp** [comment]
@cmd16 `to_dict` should be handled automatically as long as the appropriate data is registered with the `Report` instance, so that shouldn't be something that needs altering, to include positive bias output.

If you add positive bias flags to your detector, you should see that the string output from normal running of the main script shows no difference (currently, at least), whereas running with `-j` or `--json` includes new elements corresponding to the positive flags.

The other detector which is merged does not have any positive bias elements to flag, unfortunately.

I can certainly add some docs, though the tests might give some idea, if you've not looked at those in detail?

**Comment by cmd16** [comment]
Docs are just a good idea in general. I'll take a look at the tests when I get a chance

**Comment by neiljp** [comment]
@cmd FYI I added the extra bounds-check test I mentioned previously, and also in-line documentation for `Report` and updated the `Detector` guide.

**Comment by neiljp** [comment]
@j6k4m8 We currently have 2 `Detector`s merged, so I'm a little skeptical of over-engineering.
(unless others are actively in the works)

While I agree the `Flag`/`Issue` situation can be improved, I'd like to focus this PR on the bias itself. Therefore, I propose for this PR:
* moving bias into `Issue`
* revising the range to [-1.0 .. 1.0]
My only feeling against the latter is that the range is now 2.0, not 1.0, but that may never be an issue!

Considering `Flag` and `Issue` (for another PR), the other thought is perhaps to place them as separate parameters to `add_flag` of the `Report` instances, ie. `report1.add_flag(Flag(start, stop), Issue(...., bias=...)`. That would disentangle `Flag`s from `Issue`s, however we later refactor them.

@cmd16: Following @j6k4m8's suggestions (if as per above) will involve a few changes but not too significant, so broadly the docs should be similar with a slightly syntactical variation, something like:
```python
report.add_flag(Flag(start, stop, Issue("some text")), bias=Report.positive_result)
```
becoming
```python
report.add_flag(Flag(start, stop, Issue("some text", bias=Report.positive_result)))
```

**Pull request merged**
