### PR TITLE
Automatically detect Detectors at run-time; also list available, apply single Detectors, & update docs

### PR DESCRIPTION
**Pull request by neiljp**
This is what I had in mind for auto-loading of detectors, as well as @j6k4m8 ?

To have the main `gender-bias` script run your new detector:
* make a new directory in the gender-bias directory (potentially elsewhere in future, too) next to the others
* add the `__init__.py` file containing the `Detector` you write to there
* run the gender-bias script with `--use-scanned`

No adjustment to `detector.py` necessary :)

### CODE REVIEW

**Comment by j6k4m8** [comment]
I'd also take a look at `setuptools.find_packages` which could maybe make your life easier?

**Comment by neiljp** [comment]
Regarding the command-line flag, I'm open to other suggestions, including simply making it the default and doing away with the hard-coded list, but that could come as a later PR/commit if this turns out well. As such selecting an ideal name for the flag is maybe less important, though I'm totally up for that rename.

`setuptools.find_packages` looks useful, but currently the new function searches for a `Detector`-derived class, and so needs to import the module - and grabs that class for use later, too. So, it could be useful to identify the modules in the first place, but it doesn't seem a huge simplification?

**Comment by neiljp** [comment]
@j6k4m8 Could you clarify you advice/preferences in light of my comments?

**Comment by j6k4m8** [comment]
I'd say let's make it the default; I don't see a clear reason for using anything else until we have a better feel for what those subset lists of Detectors will look like.

**Comment by neiljp** [comment]
@j6k4m8 This is quite a change from the previous version, since it runs by default. However, I also added options to show the available detectors and specify a particular one from the command line.

Other than the code (not detectors though), the docs and notebooks are updated slightly based on these changes @molliem @cmd16 . Running a new Detector should be even more achievable now, though it is quick in the jupyter notebook!

**Pull request merged**
